AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB table for demo
Parameters:
  DynamoTableName:
    Type: String
    Default: demo-table
Resources:
  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Name
          Value: demo-dynamodb

Outputs:
  DynamoTableNameOut:
    Value: !Ref DemoTable
    Export:
      Name: demo-dynamodb-table-name
